name: terraform-docs-gh-actions
author: terraform-docs Authors
description: A Github action for generating Terraform module documentation using terraform-docs and gomplate.

inputs:
  config-file:
    description: Name of terraform-docs config file. To enable, provide the file name (e.g. `.terraform-docs.yml`)
    required: false
    default: "disabled"
  working-dir:
    description: Comma separated list of directories to generate docs for (ignored if `atlantis-file` or `find-dir` is set)
    required: false
    default: "."
  atlantis-file:
    description: Name of Atlantis file to extract list of directories by parsing it. To enable, provide the file name (e.g. `atlantis.yaml`)
    required: false
    default: "disabled"
  find-dir:
    description: Name of root directory to extract list of directories by running `find ./find_dir -name *.tf` (ignored if `atlantis-file` is set)
    required: false
    default: "disabled"
  output-format:
    description: terraform-docs format to generate content (see [all formats](https://github.com/terraform-docs/terraform-docs/blob/master/docs/FORMATS_GUIDE.md)) (ignored if `config-file` is set)
    required: false
    default: "markdown table"
  output-method:
    description: Method should be one of `replace`, `inject`, or `print`
    required: false
    default: "inject"
  output-file:
    description: File in module directory where the docs should be placed
    required: false
    default: "USAGE.md"
  template:
    description: When provided will be used as the template if/when the `output-file` does not exist
    default: |
      # Usage

      <!--- BEGIN_TF_DOCS --->
      <!--- END_TF_DOCS --->
    required: false
  args:
    description: Additional arguments to pass to the command (see [full documentation](https://github.com/terraform-docs/terraform-docs/tree/master/docs))
    required: false
    default: ""
  indention:
    description: Indention level of Markdown sections [1, 2, 3, 4, 5]
    required: false
    default: "2"
  git-push:
    description: If true it will commit and push the changes
    required: false
    default: "false"
  git-push-user-name:
    description: If empty the name of the GitHub Actions bot will be used (i.e. `github-actions[bot]`)
    required: false
    default: ""
  git-push-user-email:
    description: If empty the no-reply email of the GitHub Actions bot will be used (i.e. `github-actions[bot]@users.noreply.github.com`)
    required: false
    default: ""
  git-commit-message:
    description: Commit message
    required: false
    default: "terraform-docs: automated action"
  git-push-sign-off:
    description: If true it will sign-off commit
    required: false
    default: "false"
  fail-on-diff:
    description: Fail the job if there is any diff found between the generated output and existing file (ignored if `git-push` is set)
    required: false
    default: "false"

outputs:
  num_changed:
    description: Number of files changed

runs:
  using: docker
  image: "docker://quay.io/terraform-docs/gh-actions:0.7.0"
  args:
    - ${{ inputs.working-dir }}
    - ${{ inputs.atlantis-file }}
    - ${{ inputs.find-dir }}
    - ${{ inputs.output-format }}
    - ${{ inputs.output-method }}
    - ${{ inputs.output-file }}
    - ${{ inputs.template }}
    - ${{ inputs.args }}
    - ${{ inputs.indention }}
    - ${{ inputs.git-push }}
    - ${{ inputs.git-commit-message }}
    - ${{ inputs.config-file }}
    - ${{ inputs.fail-on-diff }}
    - ${{ inputs.git-push-sign-off }}
    - ${{ inputs.git-push-user-name }}
    - ${{ inputs.git-push-user-email }}

branding:
  icon: file-text
  color: gray-dark
